Repository the-djmaze/snappymail, pull requests merged in 2025-03, with the labels that each got.

#1918 Changing Gravatar hashing algorithm to sha256
  plugins/avatars/index.php
Labels: extensions (plugin)

#1891 Automatically add favicon host to CSP if present
  snappymail/v/0.0.0/app/libraries/RainLoop/Api.php
Labels: enhancement

#1880 Fix incorrect German translation
  snappymail/v/0.0.0/app/localization/de/user.json
Labels: Translation
